# Generated by Django 5.2.14 on 2026-05-17 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('processing', 'Traitement en cours'), ('saved', 'Enregistré'), ('duplicate', 'Doublon refusé'), ('pending_validation', 'En attente de validation'), ('error', 'Erreur')], db_index=True, default='processing', max_length=30)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PendingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('comparison_summary', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validé'), ('rejected', 'Refusé')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('new_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_document', to='documents.document')),
                ('old_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_replacements', to='documents.document')),
            ],
        ),
    ]
